spring:
  application:
    name: ecard
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.48.78:3306/bbyx?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mysql
    
mybatis:
  mapper-locations: classpath:mapper/*.xml
  
logging:
  level: 
    org.bgy_bbyx_dao : debug